BEGIN TRANSACTION;
CREATE TABLE REGION (
	ID INTEGER,
	NAME VARCHAR(100)
);
INSERT INTO REGION VALUES (1,'NORTHEAST');
INSERT INTO REGION VALUES (2,'MIDWEST');
INSERT INTO REGION VALUES (3,'SOUTHEAST');
INSERT INTO REGION VALUES (4,'WEST');
COMMIT;
